services:
  postgres:
    image: postgres:16.3
    container_name: literalura-postgres-db
    environment:
      POSTGRES_DB: literalura
      POSTGRES_USER: literalura
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: